# Generated by scripts/release.py (release-kit) from the v2026.10.1 release — do not edit.
class GitatlasCli < Formula
  desc "Multi-repo Git management CLI (companion to the gitatlas GUI)"
  homepage "https://github.com/grahambrooks/gitatlas-cli"
  version "2026.10.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/gitatlas-cli/releases/download/v2026.10.1/gitatlas-v2026.10.1-aarch64-apple-darwin.tar.gz"
      sha256 "61f9339882fb3ee0f9fed9f628dd606dd0236465d46a97ccc8e22509b52e32a5"
    end
    on_intel do
      url "https://github.com/grahambrooks/gitatlas-cli/releases/download/v2026.10.1/gitatlas-v2026.10.1-x86_64-apple-darwin.tar.gz"
      sha256 "2000d066d1ee263e8597be859d985aaf5a36bda347f975820451b9bba0ca00e4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/gitatlas-cli/releases/download/v2026.10.1/gitatlas-v2026.10.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "77625ae816ecf0dd6d2bc121a6f2829166d21a59f85dba039fb5f15c2ebe75e2"
    end
    on_intel do
      url "https://github.com/grahambrooks/gitatlas-cli/releases/download/v2026.10.1/gitatlas-v2026.10.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "4556191c991c372e6620f05a291eac4ee33ee4f917130a5e9624982750f36116"
    end
  end

  def install
    bin.install "gitatlas"
  end

  test do
    assert_path_exists bin/"gitatlas"
  end
end
