# Generated by scripts/release.py (release-kit) from the v2026.9.4 release — do not edit.
class GitatlasCli < Formula
  desc "Multi-repo Git management CLI (companion to the gitatlas GUI)"
  homepage "https://github.com/grahambrooks/gitatlas-cli"
  version "2026.9.4"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/gitatlas-cli/releases/download/v2026.9.4/gitatlas-v2026.9.4-aarch64-apple-darwin.tar.gz"
      sha256 "5ba0dacfb1b22fa4348d539a5fb30338e11a034375acd3e0bb420ca282112aae"
    end
    on_intel do
      url "https://github.com/grahambrooks/gitatlas-cli/releases/download/v2026.9.4/gitatlas-v2026.9.4-x86_64-apple-darwin.tar.gz"
      sha256 "6dfa680485b1d26a1ec2262fe3d5edff61ebdc90cf4241e505c85b1c1f0d9752"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/gitatlas-cli/releases/download/v2026.9.4/gitatlas-v2026.9.4-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0ea616f2bd4d83bfeb548c63d1c4b4151b3f27bae744bfb9d5890b3aa6d9f40c"
    end
    on_intel do
      url "https://github.com/grahambrooks/gitatlas-cli/releases/download/v2026.9.4/gitatlas-v2026.9.4-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "7891ec1c843498dccd7ea26af1f12b7b90ab88735d8c50610fd6a2553e8486c9"
    end
  end

  def install
    bin.install "gitatlas"
  end

  test do
    assert_path_exists bin/"gitatlas"
  end
end
